### ISSUE TITLE
[MIG] v17 Issues (26/02/2024)

### ISSUE THREAD

**Issue by sbuhl** [GoShop-Energy/lou#13]
2024-02-26 04:41:51,655 14275 INFO db_1390468 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Diff: [('account.menu_action_account_moves_all', 189, 'Accounting > Accounting > Journals > Journal Items', 275), ('industry_fsm.fsm_menu_settings_project', 538, 'Field Service > Configuration > Projects', 779)] 
2024-02-26 04:41:51,655 14275 INFO db_1390468 odoo.upgrade.base.tests.test_mock_crawl: ====================================================================== 
2024-02-26 04:41:51,655 14275 ERROR db_1390468 odoo.upgrade.base.tests.test_mock_crawl: FAIL: TestCrawler.test_check
Traceback (most recent call last):
  File "/tmp/tmpy6n_wiaa/migrations/testing.py", line 207, in test_check
    self.check(value)
  File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 139, in check
    self.assertFalse(diff, msg)
AssertionError: [('account.menu_action_account_moves_all', 189, 'Accounting > Accounting > Journals > Journal Items', 275), ('industry_fsm.fsm_menu_settings_project', 538, 'Field Service > Configuration > Projects', 779)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('account.menu_action_account_moves_all', 189, 'Accounting > Accounting > Journals > Journal Items', 275):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3814, in fetch
    self.check_access_rule('read')
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4114, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
 odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Sébastien Bühl (id=6) doesn't have 'read' access to:
- Journal Entry (account.move)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4867, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 102, in determine
    return needle(*args)
   File "/home/odoo/src/enterprise/17.0/account_accountant/models/account_move.py", line 421, in _compute_has_deferred_moves
    line.has_deferred_moves = line.move_id.deferred_move_ids
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1186, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3814, in fetch
    self.check_access_rule('read')
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4114, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
 odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Sébastien Bühl (id=6) doesn't have 'read' access to:
- Journal Entry (account.move)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3814, in fetch
    self.check_access_rule('read')
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4114, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.Sorry, Sébastien Bühl (id=6) doesn't have 'read' access to:
- Journal Entry (account.move)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 395, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 523, in mock_view_tree
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 557, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 5741, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3749, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6590, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1209, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4867, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 102, in determine
    return needle(*args)
   File "/home/odoo/src/enterprise/17.0/account_accountant/models/account_move.py", line 421, in _compute_has_deferred_moves
    line.has_deferred_moves = line.move_id.deferred_move_ids
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1186, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3814, in fetch
    self.check_access_rule('read')
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4114, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
 odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Sébastien Bühl (id=6) doesn't have 'read' access to:
- Journal Entry (account.move)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.

('industry_fsm.fsm_menu_settings_project', 538, 'Field Service > Configuration > Projects', 779):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4867, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 102, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/17.0/addons/sale_timesheet/models/project.py", line 204, in _compute_sale_order_count
    super(Project, billable_projects)._compute_sale_order_count()
   File "/home/odoo/src/odoo/17.0/addons/sale_project/models/project.py", line 99, in _compute_sale_order_count
    project.sale_order_count = len(sale_order_lines.order_id)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3831, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Sébastien Bühl (id=6) doesn't have 'read' access to:
- Sales Order Line (sale.order.line)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 395, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpy6n_wiaa/migrations/base/tests/test_mock_crawl.py", line 424, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3538, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3749, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6590, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1209, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4867, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 102, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/17.0/addons/sale_timesheet/models/project.py", line 204, in _compute_sale_order_count
    super(Project, billable_projects)._compute_sale_order_count()
   File "/home/odoo/src/odoo/17.0/addons/sale_project/models/project.py", line 99, in _compute_sale_order_count
    project.sale_order_count = len(sale_order_lines.order_id)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3831, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Sébastien Bühl (id=6) doesn't have 'read' access to:
- Sales Order Line (sale.order.line)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.
2024-02-26 04:41:51,661 14275 INFO db_1390468 odoo.upgrade.testing: Starting IntegrityCase.test_check ...
2024-02-26 04:41:51,662 14275 INFO db_1390468 odoo.upgrade.testing: skipped IntegrityCase.test_check : abstract test class
2024-02-26 04:41:51,662 14275 INFO db_1390468 odoo.upgrade.base.tests.test_moved0: Starting TestMoved0.test_check ...
2024-02-26 04:41:51,663 14275 INFO db_1390468 odoo.upgrade.testing: No value found for base.tests.test_moved0.TestMoved0, skipping check
2024-02-26 04:41:51,664 14275 INFO db_1390468 odoo.upgrade.testing: Starting IntegrityCase.test_check ...
2024-02-26 04:41:51,665 14275 INFO db_1390468 odoo.upgrade.testing: skipped IntegrityCase.test_check : abstract test class
2024-02-26 04:41:51,665 14275 INFO db_1390468 odoo.upgrade.stock.tests.test_uom_consistency: Starting TestUoMConsistencyChanges.test_check ...
2024-02-26 04:41:51,666 14275 INFO db_1390468 odoo.upgrade.testing: Calling TestUoMConsistencyChanges.check
2024-02-26 04:41:51,844 14275 INFO db_1390468 odoo.upgrade.testing: Starting IntegrityCase.test_check ...
2024-02-26 04:41:51,845 14275 INFO db_1390468 odoo.upgrade.testing: skipped IntegrityCase.test_check : abstract test class
2024-02-26 04:41:51,846 14275 INFO db_1390468 odoo.upgrade.stock.tests.test_on_hand_quantity: Starting TestOnHandQuantityUnchanged.test_check ...
2024-02-26 04:41:51,851 14275 INFO db_1390468 odoo.upgrade.testing: Calling TestOnHandQuantityUnchanged.check
2024-02-26 04:41:53,343 14275 INFO db_1390468 odoo.service.server: 15 post-tests in 135.48s, 46571 queries
2024-02-26 04:41:53,343 14275 ERROR db_1390468 odoo.tests.result: 1 failed, 0 error(s) of 15 tests when loading database 'db_1390468'
2024-02-26 04:41:53,343 14275 INFO db_1390468 odoo.service.server: Initiating shutdown
2024-02-26 04:41:53,343 14275 INFO db_1390468 odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2024-02-26 04:41:53,752 14275 INFO db_1390468 odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
Unexpected error while executing the command : ['/home/odoo/.odoo-venvs/17.0/bin/python', '/home/odoo/src/odoo/17.0/odoo-bin', '-d', 'db_1390468', '--db-filter', '^db_1390468$', '--addons-path=/home/odoo/src/odoo/17.0/addons,/home/odoo/src/odoo/17.0/odoo/addons,/home/odoo/src/enterprise/17.0,/home/odoo/src/themes/17.0', '--upgrade-path=/tmp/tmpy6n_wiaa/migrations', '--stop-after-init', '--test-tags', 'integrity_case.test_check']
command execution has failed with the error code 255

**Comment by shortcut1337** [comment]
WIP, will be done at multiple PR unless all repo are moved on same repo in goshop
https://github.com/GoShop-Energy/lou/pull/16
https://github.com/sbuhl/gse_custo/pull/44

Closing this, feel free to reopen
